# Generated by Django 2.2.7 on 2020-07-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0, verbose_name='rank')),
                ('employer', models.CharField(max_length=150, verbose_name='employer')),
                ('employeesCount', models.IntegerField(default=0, verbose_name='employeesCount')),
                ('medianSalary', models.IntegerField(default=0, verbose_name='medianSalary')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Task',
            },
        ),
    ]
